language: python
python:
    - "3.5"
sudo: required
before_install:
    - sudo apt-get update -qq
    - sudo apt-get build-dep -qq python-pygame
    - sudo apt-get install python3-dev libfreetype6-dev
install:
    - pip install -r requirements.txt
script:
    - nosetests tests/*.py
