version: '2'
services:
  pygame:
    container_name: pygame
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 arkanoid.py
    volumes:
      - .:/home/platform

